# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2939ff18b3c4976da5f549bfc1bcee94"
name = "Swiftly"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://shopify.dev/apps/default-app-home/api/auth",
  "http://localhost:5001/api/integrations/shopify/callback"
]
